# gitlab ci configuration

image: node:10.15.0

cache:
  paths:
    - node_modules/

variables:
  CI: "true"
  NODE_ENV: test

stages: 
  - test

test:
  stage: test
  script: 
   - npm install
   - npm test
